---
title       : Introduction of BMI Calculator
subtitle    : My First Slidify Presentation
author      : Q. F. Fang
job         : Coursera Learner
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Basic Function

The body mass index (BMI), or Quetelet index, is a measure of relative weight based on an individual's mass and height. Our calculator attempts to calculate your own BMI index and to interpret it in certain standards.

---
## Basic Formula
BMI=weight(kg)/height(cm)\^2*10,000


---
## Two Standards Offered
According to http://en.wikipedia.org/wiki/Body_mass_index, we offer the following two standards to interpret your BMI Index.   
1. Hongkong Standard:
Underweight	< 18.5   
Normal Range	18.5 - 22.9   
Overweight - At Risk	23.0 - 24.9   
Overweight - Moderately Obese	25.0 - 29.9   
Overweight - Severely Obese	>= 30.0   
   
2. Japan Standard   
Low  18.5 and below   
Normal	from 18.5 to 25.0 (Standard weight is 22)   
Obese (Level 1)	from 25.0 to 30.0   
Obese (Level 2)	from 30.0 to 35.0   
Obese (Level 3)	from 35.0 to 40.0   
Obese (Level 4)	40.0 and above   


---
## How to Use?
1. The BMI formula is quoted from Wikipedia: http://en.wikipedia.org/wiki/Body_mass_index
2. Click on the up or down arrow on the right side of the blanks to adjust to your height & weight (Note the units).
3. Check one of the boxes to select which standard you would like to refer to interpret your BMI index.
4. Press the "Show me!" button to submit your data. Or, your analysis will not be generated.
5. You may check ONLY ONE box. Error warning would appear to you if none or two are checked.

